### ISSUE TITLE
Item highlighting in profession bags doesn't downgrade

### ISSUE THREAD

**Issue by radhaz** [checkem/SUCC-bag#6]
In an enchantment bag everything is highlighted green/uncommon (even empty slots) unless the item is of greater value (rare/epic) which then overrides the default green highlighting. 

http://imgur.com/a/Otd9U is an example of what I'm talking about. You can see that some of the items should be white/not highlighted (like the empty slot)

**Comment by checkem** [comment]
That is the intended behaviour, the profession bags are green and the quiver, ammo pouch and soulbag are yellow, unless the item is higher than white quality. I haventthought it through, maybe I shoul've done this that all the items are highlighted due to the type of the bag, if it is not the usual bag, regardless of quality.
This is done from my perspective of convenience. This is what I am going to add to the settings, somehow.
What should it be? Should the highlight not apply to items of higher quality? Different colors?

**Comment by radhaz** [comment]
Interesting, the only profession bag I carry is the enhancement bag, I thought/expected each profession to be a different color. Since they all utilize the same color perhaps make the bags a color thats not already used by item highlighting such as magenta?

Now that I better understand how the highlighting works I think that having the bags a default magenta/red for less than uncommon and then at uncommon and above adhering to the item highlighting would be preferred? So empty slots would be red/magenta as well as junk non rare items, once they went uncommon (like greater magic essence, the highlighting would override the red/magenta for green?)
